pull_request_rules:
  - name: automatic update for PR marked as “Ready-to-Go“
    conditions:
      - -conflict # skip PRs with conflicts
      - -draft # filter-out GH draft PRs
    actions:
      update: